import "@/styles/globals.css";
import { useLocale, useTranslations } from "next-intl";
import { notFound } from "next/navigation";
import { getTranslations } from "next-intl/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { SiteHeader } from "@/components/site-header";
import { Sidebar } from "@/components/sidebar";
import { SiteFooter } from "@/components/site-footer";
import { Analytics } from "@/components/analytics";
import { ScrollTop } from "@/components/scroll-top";
import { Toaster } from "@/components/ui/toaster";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export async function generateMetadata(): Promise<Metadata> {
  const meta = await getTranslations("meta");
  return {
    title: meta("title"),
    description: meta("description"),
    viewport: meta("viewport"),
  };
}

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale?: string;
  };
}

export default function LocaleLayout({ children, params }: RootLayoutProps) {
  const locale = useLocale();
  // const t = useTranslations();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale} className={inter.className}>
      {/*<head>*/}
      {/*  <link rel="icon" href="/icon.svg" type="image/svg" sizes="256x256" />*/}
      {/*</head>*/}
      <body className="min-h-screen bg-background antialiased">
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <div className="grid md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 pr-2">
              <Sidebar className="hidden md:block" />
              <div className="md:col-span-3 lg:col-span-4 xl:col-span-5 md:border-l">
                {children}
              </div>
            </div>
            <SiteFooter />
          </div>
        </Providers>
        <TailwindIndicator />
        <Analytics />
        <ScrollTop />
        <Toaster />
        {/* Allow more height for mobile menu on mobile */}
        {/*<div className="h-40 md:hidden" />*/}
      </body>
    </html>
  );
}
